blank_issues_enabled: true
contact_links:
  - name: 💬 Discord Community
    url: https://discord.gg/74GUQDE
    about: Having problems using the webpage? Want to help with development? Join the "dr4fters" channel!
