blank_issues_enabled: true
contact_links:
  - name: 💬 Discord Community
    url: https://discord.gg/74GUQDE
    about: Running into issues on the webpage? Want to help with development? Try the Discord server!
