/* eslint-env node, mocha */
const assert = require("assert");
const parser = require("../../src/make/xml/parser");

describe("Unit tests for XML Cockatrice Parser", () => {
  describe("throw an error when xml structure not supported", () => {
    it("xml content cannot be null", () => {
      assert.throws(() => parser.parse(""), Error, "Error thrown" );
    });

    it("xml content must be valid cockatrice format", () => {
      assert.throws(() => parser.parse("<xml></xml>"), Error, "Error thrown" );
    });
  });
  describe("can parse a valid xml", () => {
    it("xml is valid", () => {
      const result = parser.parse(`<cockatrice_carddatabase version="4">
  <!--
  Created At: Wed, Nov 27 2019, 00:36:29 (UTC)
  Created By: Magic-Spoiler project @ https://github.com/Cockatrice/Magic-Spoiler

  THIS FILE IS AUTOMATICALLY GENERATED & ALL EDITS WILL BE OVERRIDDEN.
  -->
  <sets>
    <set>
      <name>PF20</name>
      <longname>MagicFest 2020</longname>
      <settype>Promo</settype>
      <releasedate>2020-01-01</releasedate>
    </set>
  </sets>
  <cards>
    <card>
      <name>Forest</name>
      <set rarity="Rare" picURL="https://img.scryfall.com/cards/normal/front/0/7/076c5ceb-4236-46ef-ba8e-336088fcedd9.jpg">PF20</set>
      <tablerow>0</tablerow>
    </card>
  </cards>
</cockatrice_carddatabase>`);
    });
  });
});

