/* eslint-env node, mocha */
const assert = require("assert");
const parser = require("../../src/make/xml/parser");

describe("Unit tests for XML Cockatrice Parser", () => {
  describe("throw an error when xml structure not supported", () => {
    it("xml content cannot be null", () => {
      assert.throws(() => parser.parse(""), Error, "Error thrown" );
    });

    it("xml content must be valid cockatrice format", () => {
      assert.throws(() => parser.parse("<xml></xml>"), Error, "Error thrown" );
    });
  });
  describe("can parse a valid xml", () => {
    it("xml is valid", () => {
      assert.throws(() => parser.parse(`
      <cockatrice_carddatabase version="4">
  <!--
  Created At: Wed, Nov 27 2019, 00:36:29 (UTC)
  Created By: Magic-Spoiler project @ https://github.com/Cockatrice/Magic-Spoiler

  THIS FILE IS AUTOMATICALLY GENERATED & ALL EDITS WILL BE OVERRIDDEN.
  -->
  <sets>
    <set>
      <name>PF20</name>
      <longname>MagicFest 2020</longname>
      <settype>Promo</settype>
      <releasedate>2020-01-01</releasedate>
    </set>
  </sets>
  <cards>
    <card>
      <name>Forest</name>
      <set rarity="Rare" picURL="https://img.scryfall.com/cards/normal/front/0/7/076c5ceb-4236-46ef-ba8e-336088fcedd9.jpg">PF20</set>
      <manacost/>
      <cmc>0.0</cmc>
      <type>Basic Land - Forest</type>
      <loyalty>None</loyalty>
      <tablerow>0</tablerow>
      <text>({T}: Add {G}.)</text>
    </card>
    <card>
      <name>Island</name>
      <set rarity="Rare" picURL="https://img.scryfall.com/cards/normal/front/2/b/2b72bbd7-0b80-4e12-86d5-494d91319ec4.jpg">PF20</set>
      <manacost/>
      <cmc>0.0</cmc>
      <type>Basic Land - Island</type>
      <loyalty>None</loyalty>
      <tablerow>0</tablerow>
      <text>({T}: Add {U}.)</text>
    </card>
    <card>
      <name>Mountain</name>
      <set rarity="Rare" picURL="https://img.scryfall.com/cards/normal/front/b/5/b56f39a5-9c58-4c04-9285-18e3b4ce78d1.jpg">PF20</set>
      <manacost/>
      <cmc>0.0</cmc>
      <type>Basic Land - Mountain</type>
      <loyalty>None</loyalty>
      <tablerow>0</tablerow>
      <text>({T}: Add {R}.)</text>
    </card>
    <card>
      <name>Path to Exile</name>
      <set rarity="Rare" picURL="https://img.scryfall.com/cards/normal/front/2/0/20298a61-2739-4254-b102-51a2a74b5ddc.jpg">PF20</set>
      <manacost>W</manacost>
      <cmc>1.0</cmc>
      <color>W</color>
      <type>Instant</type>
      <loyalty>None</loyalty>
      <tablerow>3</tablerow>
      <text>Exile target creature. Its controller may search their library for a basic land card, put that card onto the battlefield tapped, then shuffle their library.</text>
    </card>
    <card>
      <name>Plains</name>
      <set rarity="Rare" picURL="https://img.scryfall.com/cards/normal/front/3/e/3e0ae7fe-7cb0-487a-9e1e-fc2a52b42b87.jpg">PF20</set>
      <manacost/>
      <cmc>0.0</cmc>
      <type>Basic Land - Plains</type>
      <loyalty>None</loyalty>
      <tablerow>0</tablerow>
      <text>({T}: Add {W}.)</text>
    </card>
    <card>
      <name>Swamp</name>
      <set rarity="Rare" picURL="https://img.scryfall.com/cards/normal/front/4/e/4e0e3fed-c7b6-43f8-9ab5-b80bde709276.jpg">PF20</set>
      <manacost/>
      <cmc>0.0</cmc>
      <type>Basic Land - Swamp</type>
      <loyalty>None</loyalty>
      <tablerow>0</tablerow>
      <text>({T}: Add {B}.)</text>
    </card>
  </cards>
</cockatrice_carddatabase>
`), Error, "Error thrown" );
    });
  });
});

